---
title: "Project title"
subtitle: "Report"
format: html
editor: visual
execute:
  echo: true
---

**Introduction and Data:**

The data comes from sports-reference.com. The data was collected five years and was scraped from sports-reference.com by Randi Griffin, an Evolutionary Anthropology graduate student of Duke University. Randi also competed in the 2018 Winter Olympics on the Unified Korea women's national ice hockey team. This was initially made into a visualization that was then further adapted to the current data set.

The observations represent every athlete who has won a medal at the Winter Olympics. The values in each observation include the year of the Olympics, the type of event the medal was won in, the type of medal won, the country the Olympian was playing for, the gender of the Olympian, and the name of the Olympian.

**Methodology:**

Our research question is \"What are the factors that influence Winter Olympic success across countries, events and year it took place in?\"

Our research topic focuses on analyzing the performance of athletes who have won medals at the Winter Olympics. We plan to answer this research question through interference and not prediction, since we are analyzing past data that is concrete. Therefore, we do not need to predict outcomes of data since we are just inferring patterns and trends based on existing data. We plan to gather results from our data by creating visuals comparing/contrasting factors such as gender, age, Olympic event and more to see which factors affected Olympic winter success. 

\
\
